tap "homebrew/cask"
#tap "janl/homebrew-couchdb"
tap "sumcumo/utils", "git@gitlab.sumcumo.net:sumcumo/homebrew-utils"
cask_args appdir: "/Applications"

brew "gzip"
brew "pwgen"
brew "nmap"
brew "wget"
brew "htop"
brew "geoip"
brew "ansiweather"
brew "rbenv"
brew "ruby-build"
brew "cabextract"
brew "ipfs"
brew "pandoc"
brew "npm"
brew "rclone"
brew "vim"
brew "tree"
brew "fzf" 			# https://github.com/junegunn/fzf
brew "cointop"			# https://github.com/miguelmota/cointop

# CouchDB  
brew "coreutils"
brew "erlang"
brew "autoconf-archive"
brew "automake"
brew "icu4c"
#brew "spidermonkey60"

# pygame
brew "mercurial"
brew "sdl"
brew "sdl_image" 
brew "sdl_mixer"
brew "sdl_ttf" 
brew "portmidi"
brew "smpeg"

cask "font-hack-nerd-font"                     
cask "gpg-suite"
cask "iterm2"                                  
cask "tor-browser"
cask "zenmate-vpn"
cask "the-unarchiver"
cask "whatsapp"
cask "zoomus"
cask "sync"
cask "skitch"
cask "transmit"
cask "cakebrew"
cask "owasp-zap"
cask "postman"
cask "teamviewer"
cask "visual-studio-code"
cask "carbon-copy-cloner"
cask "deluge"
cask "vlc"
cask "handbrake"
cask "onyx"      	# https://www.titanium-software.fr/en/onyx.html
cask "kindle"
cask "bitmessage"	# https://bitmessage.org/wiki/Main_Page
cask "gemini"		# https://macpaw.com/gemini
cask "deepl"		# https://www.deepl.com/translator	
cask "github"
cask "signal"
cask "java"
cask "telegram"
cask "anaconda"
cask "itsycal"
cask "rcloneosx"
cask "rsyncosx"
cask "micro-snitch"
cask "osxfuse"
cask "dozer"		# https://github.com/Mortennn/Dozer
cask "mattermost"
